#!/bin/bash

if [[ $* == *--help* ||  $* == *-h* ]]; then
  echo "Usage: $0 [bot_version] [destination_folder]"
  echo "Example: $0 1.9.0.0.2668 /home/triplea/bots"
  echo "bot_version: Bot version which should be installed. Use 'latest' or leave blank to install the newest version."
  echo "destination_folder: Bot installation location. Defaults to /home/triplea/bots"
  exit 0
fi

cd $(dirname $0)

BOT_VERSION=${1:-'latest'}
DESTINATION_FOLDER=${2:-'/home/triplea/bots'}

set -eu

#Retrieve latest triplea version
if [[ "$BOT_VERSION" == "latest" ]]; then
  BOT_VERSION=$(curl -s 'https://api.github.com/repos/triplea-game/triplea/releases/latest' | python3 -c "import sys, json; print(json.load(sys.stdin)['tag_name'])")
fi

VERSION_FILE="$DESTINATION_FOLDER/version"
if [[ ! ($* == *--force* || $* == *-f*) && -f "$VERSION_FILE" && "$BOT_VERSION" == "$(<$VERSION_FILE)" ]]; then
  echo "Version $BOT_VERSION is already installed"
  echo "Run with -f or --force to force the installation"
  exit 0
fi

FILE_SUFFIX="all_platforms.zip"
DOWNLOAD_URL="https://github.com/triplea-game/triplea/releases/download/$BOT_VERSION/triplea-$BOT_VERSION-$FILE_SUFFIX"
echo "Download from $DOWNLOAD_URL"
wget $DOWNLOAD_URL

FILE=$(ls | grep "$BOT_VERSION-$FILE_SUFFIX$")

mkdir -p $DESTINATION_FOLDER
echo "$BOT_VERSION" > $DESTINATION_FOLDER/version

echo "Unpacking $FILE to: $DESTINATION_FOLDER"
unzip -o -d $DESTINATION_FOLDER $FILE
rm $FILE

# copy scripts
SCRIPT_HOME=($(cd $(dirname $0) && pwd))
cp "$SCRIPT_HOME/run_bot" "$DESTINATION_FOLDER"
cp "$SCRIPT_HOME/uninstall_bot" "$DESTINATION_FOLDER"

sed "s|BOT_DIR|$DESTINATION_FOLDER|" "./triplea-bot@.service" > "./triplea-bot@.service.custom"
sudo mv "./triplea-bot@.service.custom" "/lib/systemd/system/triplea-bot@.service"
sudo systemctl daemon-reload

sudo chown -R triplea:triplea $DESTINATION_FOLDER

echo "You can start bots by typing 'sudo service triplea-bot@BOT_NUMBER start' or 'sudo systemctl start triplea-bot@BOT_NUMBER'"
