#!/bin/bash

LOBBY_VERSION=$1
DESTINATION_FOLDER=$2

set -eu


function usage() {
  echo "usage: $(basename $0) [lobby_version] [destination_folder]"
  echo " lobby_zip_url: download location for the lobby zip install folder"
  echo " destination_folder: where to install the lobby"
  exit -1
}

if [[ -z "$LOBBY_VERSION" || -z "$DESTINATION_FOLDER" ]]; then
  usage;
fi

DOWNLOAD_URL="https://github.com/triplea-game/triplea/releases/download/$LOBBY_VERSION/triplea-$LOBBY_VERSION-server.zip"
echo "Download from $DOWNLOAD_URL"
wget $DOWNLOAD_URL


FILE=$(ls | grep "$LOBBY_VERSION-server.zip$")

TARGET_FOLDER=$DESTINATION_FOLDER/lobby_$LOBBY_VERSION
mkdir -p $TARGET_FOLDER
echo "Unpacking $FILE to: $TARGET_FOLDER" 

unzip -D $TARGET_FOLDER $FILE
rm $FILE


# copy the run_lobby script, should be in same same folder as this script
cp run_lobby $TARGET_FOLDER

## assume we're running as triplea
#sudo chown -R triplea:triplea $TARGET_FOLDER
