#!/bin/bash

if [[ $* == *--help* ||  $* == *-h* ]]; then
  echo "Usage: $(basename $0) [lobby_version] [destination_folder]"
  echo "Example: $0 1.9.0.0.2668 /home/triplea/lobby"
  echo "lobby_version: triplea-version of the lobby. Set to latest or leave blank to install the latest version"
  echo "destination_folder: Installation folder of the lobby. Defaults to /home/triplea/lobby"
  exit 0
fi

cd $(dirname $0)

LOBBY_VERSION=${1:-'latest'}
DESTINATION_FOLDER=${2:-'/home/triplea/lobby'}

set -eu

#Retrieve latest triplea version
if [[ "$LOBBY_VERSION"== "latest" ]]; then
  LOBBY_VERSION=$(curl -s 'https://api.github.com/repos/triplea-game/triplea/releases/latest' | python3 -c "import sys, json; print(json.load(sys.stdin)['tag_name'])")
fi

VERSION_FILE="$DESTINATION_FOLDER/version"
if [[ ! ($* == *--force* || $* == *-f*) && -f "$VERSION_FILE" && "$LOBBY_VERSION" == "$(<$VERSION_FILE)" ]]; then
  echo "Version $LOBBY_VERSION is already installed"
  echo "Run with -f or --force to force the installation"
  exit 0
fi

DOWNLOAD_URL="https://github.com/triplea-game/triplea/releases/download/$LOBBY_VERSION/triplea-$LOBBY_VERSION-server.zip"
echo "Download from $DOWNLOAD_URL"
wget $DOWNLOAD_URL

FILE=$(ls | grep "$LOBBY_VERSION-server.zip$")

mkdir -p $DESTINATION_FOLDER
echo "$LOBBY_VERSION" > $DESTINATION_FOLDER/version

echo "Unpacking $FILE to: $DESTINATION_FOLDER"
unzip -d $DESTINATION_FOLDER $FILE -o
rm $FILE

# copy the run_lobby script, should be in same same folder as this script
cp ./run_lobby "$DESTINATION_FOLDER"
cp ./uninstall_lobby "$DESTINATION_FOLDER"

sed "s|LOBBY_DIR|$DESTINATION_FOLDER|" "./triplea-lobby.service" > "./triplea-lobby.service.custom"
sudo mv "./triplea-lobby.service.custom" "/lib/systemd/system/triplea-lobby.service"
sudo systemctl enable triplea-lobby
sudo systemctl daemon-reload

sudo chown -R triplea:triplea $DESTINATION_FOLDER

echo "You can now start the lobby using 'sudo service triplea-lobby start' or 'sudo systemctl start triplea-lobby'"
