#!/bin/bash

if [[ $* == *--help* ||  $* == *-h* ]]; then
  echo "Usage: $(basename $0) [version]"
  echo "Example: $(basename $0) 1.9.0.0.3500"
  exit 0
fi

cd $(dirname $0)

chmod +x ./*

VERSION=${1:-'latest'}

## get all maps
mkdir -p ./maps
cd ./maps
../download_all_maps
cd ../
mkdir -p /home/triplea/bots
cp ./maps /home/triplea/bots

## install bot game engine
./install_bot $VERSION /home/triplea/bots
