#!/bin/bash

VERSION=$1

if [ -z "$VERSION" ]; then
  echo "usage: $(basename $0) [version]"
  echo " example: $(basename $0) 1.9.0.0.3500"
  exit 1  
fi

## get all maps
mkdir -p bots/maps
cd bots/maps
../../download_all_maps
cd ../../

## install bot game engine
./install_bot $VERSION bots/
vim bots/*/run_bot

## mv installed files to triplea user home folder 
sudo mv bots/ /home/triplea/
sudo chown -R triplea:triplea /home/triplea/bots/

