#!/bin/bash

## local port on this machine that the bot can use for receiving traffic
PORT=$1

## the number that will be assigned to the bot server, basically
## the id and name of the bot server.
BOT_NUMBER=$2

set -eu

BOT_NAME=NJ_WarClub
PATH_TO_MAPS_FOLDER="../maps"

LOBBY_HOST=45.79.144.53
LOBBY_PORT=3304

BOT_FULL_NAME="Bot${BOT_NUMBER}_${BOT_NAME}"

if [[ -z "$PORT" ]] || [[ -z "$BOT_NUMBER" ]]; then
 echo "usage: $(basename $0) [bot_port] [bot_number]"
 exit -1
fi

cd $(dirname $0)
java -server -Xmx320m -Djava.awt.headless=true -classpath bin/triplea.jar games.strategy.engine.framework.headlessGameServer.HeadlessGameServer triplea.game.host.console=false triplea.game= triplea.server=true triplea.port=$PORT triplea.lobby.host=$LOBBY_HOST triplea.lobby.port=$LOBBY_PORT triplea.name=${BOT_FULL_NAME} triplea.lobby.game.hostedBy=${BOT_FULL_NAME} triplea.lobby.game.supportEmail=Nobody@hotmail123.com triplea.lobby.game.comments="bot server ${BOT_NUMBER}" triplea.lobby.game.reconnection=172800 mapFolder=${PATH_TO_MAPS_FOLDER}

