#!/bin/bash

cd $(dirname $0)
java -server -Xmx320m -Djava.awt.headless=true -classpath bin/triplea.jar games.strategy.engine.framework.headlessGameServer.HeadlessGameServer triplea.game.host.console=false triplea.game= triplea.server=true triplea.port=4401 triplea.lobby.host=45.79.144.53 triplea.lobby.port=3304 triplea.name=Bot1_TripleAWarClub triplea.lobby.game.hostedBy=Bot1_TripleAWarClub triplea.lobby.game.supportEmail=Nobody@hotmail123.com triplea.lobby.game.comments="automated_host" triplea.lobby.game.reconnection=172800 mapFolder=../maps

