#!/bin/bash


## Bot number to be assigned to the current bot.
## This updated both the port number the bot runs on,
## and the name of the bot.
BOT_NUMBER=$1

set -eu 

PORT="400$BOT_NUMBER"

if [ -z "$BOT_NUMBER" ]; then
  echo "Usage: $(basename $0) (bot number)"
  exit
fi

sudo ufw allow $PORT
sudo ufw reload
sudo -u triplea nohup ./run_bot $PORT $BOT_NUMBER &
