#!/bin/bash

UNINSTALL_LOBBY="uninstall_lobby"
UNINSTALL_LOBBY_URL="https://raw.githubusercontent.com/triplea-game/lobby/master/files/lobby/$UNINSTALL_LOBBY"

RUN_LOBBY="run_lobby"
RUN_LOBBY_URL="https://raw.githubusercontent.com/triplea-game/lobby/master/files/lobby/run_lobby"

DOWNLOAD_FILE="triplea-$LOBBY_VERSION-server.zip"
DOWNLOAD_FILE_URL="https://github.com/triplea-game/triplea/releases/download/$LOBBY_VERSION/$DOWNLOAD_FILE"

SERVICE_FILE="triplea-lobby.service"
SERVICE_FILE_URL="https://raw.githubusercontent.com/triplea-game/lobby/master/files/lobby/triplea-lobby.service" 
SERVICE_FILE_PATH="/lib/systemd/system/$SERVICE_FILE"


if [[ $USER != "root" ]]; then
  echo "This script must be run as root"
  echo "Type 'sudo $0'"
  exit 1
fi

function usage() {
  echo "Usage: $(basename $0) [lobby_version] [port] [destination_folder]"
  echo "Example: $0 1.9.0.0.2668 3303 /home/triplea/lobby"
  echo "Example: $0 latest 3304
  echo "  port: port to run the lobby on
  echo "  lobby_version: triplea-version of the lobby. Set to latest or leave blank to install the latest version"
  echo "  destination_folder: Installation folder of the lobby. Defaults to /home/triplea/lobby"
  exit 1
}

if [[ $* == *--help* ||  $* == *-h* ]]; then
  usage
fi

LOBBY_VERSION=${1:-'latest'}
PORT=${2:-'3303'}
DESTINATION_FOLDER=${3:-'/home/triplea/lobby'}

set -eu


grep -q triplea /etc/passwd || adduser triplea

apt -y install openjdk-8-jre openjfx python3 curl unzip postgresql postgresql-contrib \
   cowsay htop iftop tiptop fail2ban unattended-upgrades vim

echo "Input the postgres DB password"

ufw allow 22 $PORT
echo "y" | ufw enable

# Retrieve latest triplea version
if [[ "$LOBBY_VERSION" == "latest" ]]; then
  LOBBY_VERSION=$(curl -s 'https://api.github.com/repos/triplea-game/triplea/releases/latest' \
        | python3 -c "import sys, json; print(json.load(sys.stdin)['tag_name'])")
fi

DESTINATION_FOLDER=$DESTINATION_FOLDER/$LOBBY_VERSION
mkdir -p $DESTINATION_FOLDER

curl $DOWNLOAD_FILE_URL > $DOWNLOAD_FILE
unzip -o -d $DESTINATION_FOLDER $DOWNLOAD_FILE
rm $DOWNLOAD_FILE


curl $RUN_LOBBY_URL > $DESTINATION_FOLDER/$RUN_LOBBY
curl $UNINSTALL_LOBBY_URL > $DESTINATION_FOLDER/$UNINSTALL_LOBBY
chmod +x $DESTINATION_FOLDER/$RUN_LOBBY $DESTINATION_FOLDER/$UNINSTALL_LOBBY


curl $SERVICE_FILE_URL > $SERVICE_FILE_PATH
sed -i "s|LOBBY_DIR|$DESTINATION_FOLDER|" $SERVICE_FILE_PATH

systemctl enable triplea-lobby
systemctl daemon-reload

chown -R triplea:triplea /home/triplea

# while -z "$DB_PASSWORD"; do
#  echo -n "Enter DB password: "
#  read -s DB_PASSWORD
# done;


echo "Start lobby with: 'sudo service triplea-lobby start', can also do 'stop|restart' as well" > /home/triplea/LOBBY-README.txt
