#!/bin/bash

CURL="curl -L"

UNINSTALL_LOBBY="uninstall_lobby"
UNINSTALL_LOBBY_URL="https://raw.githubusercontent.com/triplea-game/lobby/master/files/lobby/$UNINSTALL_LOBBY"

RUN_LOBBY="run_lobby"
RUN_LOBBY_URL="https://raw.githubusercontent.com/triplea-game/lobby/master/files/lobby/run_lobby"

SERVICE_FILE="triplea-lobby.service"
SERVICE_FILE_URL="https://raw.githubusercontent.com/triplea-game/lobby/master/files/lobby/triplea-lobby.service" 
SERVICE_FILE_PATH="/lib/systemd/system/$SERVICE_FILE"

if [[ $USER != "root" ]]; then
  echo "This script must be run as root"
  echo "Type 'sudo $0'"
  exit 1
fi

function usage() {
  echo "Usage: $(basename $0) [lobby_version] [port] [destination_folder]"
  echo "Example: $0 1.9.0.0.2668 3303 /home/triplea/lobby"
  echo "Example: $0 latest 3304"
  echo "  lobby_version: TripleA version of the lobby. Set to latest or leave blank to install the latest version"
  echo "  port: Port to run the lobby on. Defaults to 3304"
  echo "  destination_folder: Installation folder of the lobby. Defaults to /home/triplea/lobby"
  exit 1
}

if [[ $* == *--help* ||  $* == *-h* ]]; then
  usage
fi

LOBBY_VERSION=${1:-'latest'}
PORT=${2:-'3304'}
DESTINATION_FOLDER=${3:-'/home/triplea/lobby'}

set -eux

grep -q triplea /etc/passwd || adduser triplea

grep -q "^triplea" /etc/sudoers || echo "triplea ALL=(ALL) /usr/sbin/service triplea-lobby" >> /etc/sudoers
grep -q "^triplea.*htop" /etc/sudoers || echo "triplea ALL=(ALL) /usr/bin/htop*" >> /etc/sudoers
grep -q "^triplea.*iftop" /etc/sudoers || echo "triplea ALL=(ALL) /usr/bin/iftop" >> /etc/sudoers

apt -y install openjdk-8-jre openjfx python3 curl unzip postgresql postgresql-contrib \
   cowsay htop iftop tiptop fail2ban unattended-upgrades vim

ufw allow 22
ufw allow $PORT
echo "y" | ufw enable

# Retrieve latest triplea version
if [[ "$LOBBY_VERSION" == "latest" ]]; then
  LOBBY_VERSION=$($CURL -s 'https://api.github.com/repos/triplea-game/triplea/releases/latest' \
        | python3 -c "import sys, json; print(json.load(sys.stdin)['tag_name'])")
fi

DESTINATION_FOLDER=$DESTINATION_FOLDER/$LOBBY_VERSION
mkdir -p $DESTINATION_FOLDER

echo "$LOBBY_VERSION" > $DESTINATION_FOLDER/version

LOBBY_INSTALLER_FILE="triplea-$LOBBY_VERSION.zip"
$CURL "https://github.com/triplea-game/triplea/releases/download/$LOBBY_VERSION/triplea-$LOBBY_VERSION-server.zip" > $LOBBY_INSTALLER_FILE
unzip -o -d $DESTINATION_FOLDER $LOBBY_INSTALLER_FILE
rm $LOBBY_INSTALLER_FILE
chmod go-rw $DESTINATION_FOLDER/config/lobby/lobby.properties

$CURL $RUN_LOBBY_URL > $DESTINATION_FOLDER/$RUN_LOBBY
$CURL $UNINSTALL_LOBBY_URL > $DESTINATION_FOLDER/$UNINSTALL_LOBBY
chmod +x $DESTINATION_FOLDER/$RUN_LOBBY $DESTINATION_FOLDER/$UNINSTALL_LOBBY

$CURL $SERVICE_FILE_URL > $SERVICE_FILE_PATH
sed -i "s|LOBBY_DIR|$DESTINATION_FOLDER|" $SERVICE_FILE_PATH

systemctl enable triplea-lobby
systemctl daemon-reload

chown -R triplea:triplea /home/triplea

echo "Make sure to update the DB password in: $DESTINATION_FOLDER/config/lobby/lobby.properties"

echo "Start lobby with: 'sudo service triplea-lobby start', can also do 'stop|restart' as well" \
   | tee /home/triplea/LOBBY-README.txt
