#!/bin/bash

NEW_USER=$1

set -u
if [ -z "$NEW_USER" ]; then
 echo "usage: $(basename $0) [new_user_name]"
 echo " new_user_name: name of the very first user to create."
 exit 1
fi

echo "We assume you are running as root and are on a brand new server."
sudo echo "yes";


## install java (ref: http://tecadmin.net/install-java-8-on-debian/#)

echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" > /etc/apt/sources.list.d/java-8-debian.list
echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" >> /etc/apt/sources.list.d/java-8-debian.list

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886
sudo apt-get update
sudo apt-get install -y oracle-java8-installer ufw git htop iftop \
   fail2ban unattended-upgrades unzip default-jre vim

ufw allow 22
ufw enable 

 ## add triplea user
useradd triplea
passwd -l triplea
mkdir -p /home/triplea
chown -R tripea:triplea /home/triplea


 ## add first admin user
useradd $NEW_USER
passwd -l $NEW_USER
mkdir -p /home/$NEW_USER/.ssh/
chmod 700 /home/$NEW_USER/.ssh

touch /home/$NEW_USER/.ssh/authorized_keys
chmod 400 /home/$NEW_USER/.ssh/authorized_keys
   
chown $NEW_USER:$NEW_USER /home/$NEW_USER -R

 
# security ref: https://plusbryan.com/my-first-5-minutes-on-a-server-or-essential-security-for-linux-servers
sed -i 's/^PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
sed -i 's/^PasswordAuthentication.*/PasswordAuthenitcation no/' /etc/ssh/sshd_config

vi /home/$NEW_USER/.ssh/authorized_keys
echo "Turned off password login, make sure you can passwordless SSH to this server before logging off."
echo "Otherwise now install maps and bot"


echo "install yourself as an admin"
echo "$NEW_USER            ALL = (ALL) NOPASSWD:ALL"
read
visudo
service ssh restart


echo "Okay, now check that you have passwordless login to this server, and sudo"
echo "Once good, next step is to run 'install_all'"
echo "Congrats, server setup is complete"
