#!/bin/bash

## local port on this machine that the bot can use for receiving traffic
PORT=$1

## the number that will be assigned to the bot server, basically
## the id and name of the bot server.
BOT_NUMBER=$2
BOT_NAME=$3
LOBBY_HOST=${4:-'45.79.144.53'}
LOBBY_PORT=${5:-'3304'}

set -eu

BOT_FULL_NAME="Bot${BOT_NUMBER}_${BOT_NAME}" ## must start with "Bot"
COMMENT="automated_host ${BOT_NUMBER}" ## must contain "automated_host"


if [[ -z "$PORT" || -z "$BOT_NUMBER" ]]; then
 echo "Usage: $(basename $0) bot_port bot_number [lobby_host] [lobby_port]"
 exit -1
fi

cd $(dirname $0)
java -server -Xmx320m -Djava.awt.headless=true -classpath "bin/*" games.strategy.engine.framework.headlessGameServer.HeadlessGameServer \
-Ptriplea.game.host.console=false -Ptriplea.game= -Ptriplea.server=true -Ptriplea.port=$PORT -Ptriplea.lobby.host=$LOBBY_HOST -Ptriplea.lobby.port=$LOBBY_PORT \
-Ptriplea.name=${BOT_FULL_NAME} -Ptriplea.lobby.game.hostedBy=${BOT_FULL_NAME} -Ptriplea.lobby.game.supportEmail=Nobody@hotmail123.com \
-Ptriplea.lobby.game.comments="${COMMENT}" -Ptriplea.lobby.game.reconnection=172800 -PmapFolder=/home/triplea/maps
