#!/bin/bash

## local port on this machine that the bot can use for receiving traffic
PORT=$1

## the number that will be assigned to the bot server, basically
## the id and name of the bot server.
BOT_NUMBER=$2
BOT_NAME=$3
LOBBY_HOST=${4:-'45.79.144.53'}
LOBBY_PORT=${5:-'3304'}

set -eu

BOT_FULL_NAME="Bot${BOT_NUMBER}_${BOT_NAME}" ## must start with "Bot"
COMMENT="automated_host ${BOT_NUMBER}" ## must contain "automated_host"


if [[ -z "$PORT" || -z "$BOT_NUMBER" ]]; then
 echo "Usage: $(basename $0) bot_port bot_number [lobby_host] [lobby_port]"
 exit -1
fi

mkdir -p logs

cd $(dirname $0)
java -server -Xmx320m -Djava.awt.headless=true -classpath bin/triplea.jar games.strategy.engine.framework.headlessGameServer.HeadlessGameServer triplea.game.host.console=false triplea.game= triplea.server=true triplea.port=$PORT triplea.lobby.host=$LOBBY_HOST triplea.lobby.port=$LOBBY_PORT triplea.name=${BOT_FULL_NAME} triplea.lobby.game.hostedBy=${BOT_FULL_NAME} triplea.lobby.game.supportEmail=Nobody@hotmail123.com triplea.lobby.game.comments="${COMMENT}" triplea.lobby.game.reconnection=172800 mapFolder=../maps

