#!/bin/bash

# Downloads all currently available tripleA map zip files to the current directory

for i in $(curl --silent https://raw.githubusercontent.com/triplea-game/triplea/master/triplea_maps.yaml | grep url | sed 's/^-*\s*url: //' | grep "^https"); do
 MAP_NAME=$(echo $i | sed 's|/archive.*||' | sed 's|.*/||')
 wget -O $MAP_NAME-master.zip $i
done;

#TODO change this script to use the GitHub API, once we no longer use the triplea_maps.yaml file
