#!/bin/bash -e
#
# Creates an empty lobby database for production.
#

readonly db_user=postgres

read -p "Enter password for database user '$db_user': " -s db_password
echo
PGPASSWORD="$db_password" psql -h localhost -U $db_user <<EOF
  CREATE DATABASE ta_users;
EOF
