#!/bin/bash -e
#
# Creates an empty lobby database.
#

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <db_name>"
  echo
  echo "  db_name: The name of the database to create."
  exit 1
fi

readonly db_name=$1
readonly db_user=postgres

read -p "Enter password for database user '$db_user': " -s db_password
echo
PGPASSWORD="$db_password" psql -h localhost -U $db_user <<EOF
  CREATE DATABASE $db_name;
EOF
