#!/bin/bash

PORT=${1:-'3304'}
RAM=${2:-'256M'}

cd $(dirname $0)
java -server -Xmx$RAM -Xms$RAM -classpath bin/triplea.jar:lib/derby-10.10.1.1.jar -Dtriplea.lobby.port=$PORT games.strategy.engine.lobby.server.LobbyServer
